-- ============================================================================
-- 0024_platform_prive — edifio Sourcing (2026-05-27)
-- ----------------------------------------------------------------------------
-- Objectif : ajouter la valeur 'prive' a l'enum platform_code.
--
-- Source de verite :
--   - src/db/schema/enums.ts (enum `platformCode` etendu)
--   - src/app/sourcing/ao/nouveau/ (formulaire creation AO manuel)
--
-- IMPORTANT — ALTER TYPE ... ADD VALUE et les transactions Postgres :
--   `ADD VALUE` ne peut PAS etre utilise dans la meme transaction que
--   l'INSERT/UPDATE qui consomme la nouvelle valeur (Postgres 12+ accepte
--   ADD VALUE dans une TX, mais la nouvelle valeur n'est PAS visible pour
--   les DML de la meme TX — cf. fix/enum-platform-code-ci).
--
--   Fix : ce fichier ne contient QUE l'ADD VALUE. Le seed (INSERT INTO
--   platforms) est isole dans la migration suivante : 0026_platform_prive_seed.
--
--   `IF NOT EXISTS` : idempotence — re-jouable sans erreur si la valeur
--   existe deja (migration partielle, patch prod manuel, etc.).
-- ============================================================================

ALTER TYPE "public"."platform_code" ADD VALUE IF NOT EXISTS 'prive';
